import streamlit as st
import pandas as pd
import numpy as np
import os
import io
from src.config import *
from src.train import train_pipeline
from src.predict import run_prediction
from src.dashboard import plot_class_distribution, plot_antibiotic_resistance, plot_feature_importance
from src.recommend import get_recommendations
from src.validators import validate_uploaded_file
from src.utils import load_metadata, load_preprocessor, load_model
from src.explain import get_feature_importances

# Page Config
st.set_page_config(page_title="ResistAI | AMR Prediction", page_icon="🧬", layout="wide")

# Load CSS
def load_css():
    try:
        with open("assets/styles.css") as f:
            st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
    except FileNotFoundError:
        pass

load_css()

# Disclaimer
def render_disclaimer():
    st.markdown("""
    <div class="disclaimer">
        <strong>⚠️ MEDICAL DISCLAIMER:</strong> This application is a prototype built for educational and biohackathon purposes only. 
        It is NOT a medical diagnostic tool. Predictions generated by this system should absolutely not be used for real clinical decision-making or prescribing.
    </div>
    """, unsafe_allow_html=True)

st.title("🧬 ResistAI")
st.subheader("AI-Powered Antibiotic Resistance Prediction & Decision Support System")
render_disclaimer()

# Navigation
tabs = st.tabs(["🏠 Home", "📊 Data & Train", "🔮 Predict", "📈 Dashboard", "ℹ️ About"])

# ====================
# TAB 1: HOME
# ====================
with tabs[0]:
    st.markdown("""
    ### Welcome to ResistAI
    Antimicrobial resistance (AMR) is a global health crisis. ResistAI is an educational prototype that uses machine learning to predict whether a bacterial isolate will be **Resistant (R)**, **Susceptible (S)**, or **Intermediate (I)** to specific antibiotics based on tabular datasets.
    
    #### Key Features
    - **Upload & Train**: Bring your own tabular AMR data or use our synthetic sample.
    - **ML Pipeline**: Automated preprocessing, missing value handling, and robust model training.
    - **Explainable AI**: Understand what features drive the predictions.
    - **Decision Support**: Contextual recommendations based on predicted susceptibility.
    
    #### How to get started:
    1. Go to the **Data & Train** tab to train a model.
    2. Then head to **Predict** to test single isolates or batch CSV.
    """)
    
    if os.path.exists(SAMPLE_DATA_PATH):
        st.success("✅ Sample synthetic dataset found locally. You can use it right away in the 'Data & Train' tab.")

# ====================
# TAB 2: DATA & TRAIN
# ====================
with tabs[1]:
    st.header("Data Upload & Model Training")
    
    data_source = st.radio("Choose Data Source", ["Use Synthetic Sample Dataset", "Upload CSV"])
    
    df = None
    if data_source == "Use Synthetic Sample Dataset":
        if os.path.exists(SAMPLE_DATA_PATH):
            df = pd.read_csv(SAMPLE_DATA_PATH)
            st.success("Sample dataset loaded.")
        else:
            st.error("Sample dataset not found. Try generating it first.")
    else:
        uploaded_file = st.file_uploader("Upload AMR CSV Dataset", type=['csv'])
        if uploaded_file is not None:
            df = pd.read_csv(uploaded_file)
            is_valid, errors = validate_uploaded_file(df)
            if is_valid:
                st.success("File uploaded successfully.")
            else:
                for e in errors:
                    st.error(e)
                df = None
                
    if df is not None:
        with st.expander("Preview Data", expanded=True):
            st.dataframe(df.head())
            st.write(f"Shape: {df.shape[0]} rows, {df.shape[1]} columns")
            
        st.subheader("Train Prediction Model")
        target_col = st.selectbox("Select Target Column (Susceptibility Label)", df.columns, index=len(df.columns)-1)
        model_type = st.selectbox("Select Model", ["RandomForest", "XGBoost"])
        
        if st.button("Train Model 🚀"):
            with st.spinner("Training model in the background..."):
                try:
                    model, preprocessor, metadata, eval_metrics = train_pipeline(df, target_col=target_col, model_type=model_type)
                    st.success("Model trained and saved successfully!")
                    
                    st.subheader("Evaluation Metrics")
                    col1, col2, col3, col4 = st.columns(4)
                    col1.metric("Accuracy", f"{eval_metrics['accuracy']:.2%}")
                    col2.metric("Precision", f"{eval_metrics['precision']:.2%}")
                    col3.metric("Recall", f"{eval_metrics['recall']:.2%}")
                    col4.metric("F1 Score", f"{eval_metrics['f1_score']:.2%}")
                    
                    with st.expander("View Classification Report"):
                        report_df = pd.DataFrame(eval_metrics['classification_report']).transpose()
                        st.dataframe(report_df)
                        
                except Exception as e:
                    st.error(f"Error during training: {e}")

# ====================
# TAB 3: PREDICT
# ====================
with tabs[2]:
    st.header("Predict Resistance")
    
    if os.path.exists(MODEL_PATH) and os.path.exists(METADATA_PATH):
        metadata = load_metadata(METADATA_PATH)
        st.info(f"Using trained **{metadata['model_type']}** model.")
        
        pred_mode = st.radio("Prediction Mode", ["Manual Input", "Batch Upload"])
        
        if pred_mode == "Manual Input":
            st.subheader("Patient/Isolate Data Entry")
            input_data = {}
            features = metadata['features']
            
            with st.form("prediction_form"):
                cols = st.columns(3)
                for i, feat in enumerate(features):
                    with cols[i % 3]:
                        if feat in metadata['num_features']:
                            input_data[feat] = st.number_input(f"{feat}", value=0.0)
                        else:
                            # Try to infer categoricals from sample data if available, else text input
                            if os.path.exists(SAMPLE_DATA_PATH):
                                sample_df = pd.read_csv(SAMPLE_DATA_PATH)
                                if feat in sample_df.columns:
                                    unique_vals = sample_df[feat].dropna().unique().tolist()
                                    input_data[feat] = st.selectbox(f"{feat}", unique_vals + ["Other"])
                                    if input_data[feat] == "Other":
                                        input_data[feat] = st.text_input(f"{feat} (Custom)")
                                else:
                                    input_data[feat] = st.text_input(f"{feat}")
                            else:
                                input_data[feat] = st.text_input(f"{feat}")
                                
                submit = st.form_submit_button("Predict Outcome")
                
            if submit:
                input_df = pd.DataFrame([input_data])
                try:
                    res_df = run_prediction(input_df, MODEL_PATH, PREPROCESSOR_PATH, METADATA_PATH)
                    pred = res_df['Predicted_Class'][0]
                    conf = res_df['Confidence_%'][0]
                    
                    st.subheader("Prediction Result")
                    
                    color = "red" if pred == "Resistant" else "green" if pred == "Susceptible" else "orange"
                    st.markdown(f"### <span style='color:{color}'>{pred}</span> ({conf}%)", unsafe_allow_html=True)
                    
                    st.subheader("AI Decision Support Suggestions")
                    species = input_data.get('Species', None)
                    recs = get_recommendations(pred, conf, species)
                    st.markdown('<div class="recommendation-card">', unsafe_allow_html=True)
                    for r in recs:
                        st.markdown(r)
                    st.markdown('</div>', unsafe_allow_html=True)
                    
                except Exception as e:
                    st.error(f"Prediction Error: {e}")
                    
        else:
            batch_file = st.file_uploader("Upload CSV for Batch Prediction", type=['csv'])
            if batch_file:
                batch_df = pd.read_csv(batch_file)
                if st.button("Run Batch Prediction"):
                    with st.spinner("Processing..."):
                        try:
                            results = run_prediction(batch_df, MODEL_PATH, PREPROCESSOR_PATH, METADATA_PATH)
                            st.dataframe(results.head(10))
                            
                            csv_res = results.to_csv(index=False).encode('utf-8')
                            st.download_button("Download Predictions CSV", data=csv_res, file_name="predictions_output.csv", mime="text/csv")
                        except Exception as e:
                            st.error(f"Batch prediction error: {e}")
                            
    else:
        st.warning("No trained model found. Please train a model in the 'Data & Train' tab first.")

# ====================
# TAB 4: DASHBOARD
# ====================
with tabs[3]:
    st.header("Analytics & Insights")
    
    if os.path.exists(SAMPLE_DATA_PATH):
        df = pd.read_csv(SAMPLE_DATA_PATH)
        
        target_col = None
        if os.path.exists(METADATA_PATH):
            target_col = load_metadata(METADATA_PATH).get('target_col', 'Susceptibility')
        else:
            target_col = 'Susceptibility' if 'Susceptibility' in df.columns else df.columns[-1]
            
        col1, col2 = st.columns(2)
        
        with col1:
            fig1 = plot_class_distribution(df, target_col)
            if fig1: st.plotly_chart(fig1, use_container_width=True)
            
        with col2:
            fig2 = plot_antibiotic_resistance(df)
            if fig2: st.plotly_chart(fig2, use_container_width=True)
            
        st.subheader("Feature Importance (Global Explanations)")
        if os.path.exists(MODEL_PATH) and os.path.exists(PREPROCESSOR_PATH):
            model = load_model(MODEL_PATH)
            prep = load_preprocessor(PREPROCESSOR_PATH)
            meta = load_metadata(METADATA_PATH)
            
            fi_df = get_feature_importances(model, prep, meta)
            if fi_df is not None:
                fig3 = plot_feature_importance(fi_df)
                if fig3: st.plotly_chart(fig3, use_container_width=True)
            else:
                st.info("Feature importance not supported by this model.")
    else:
        st.warning("Generate or upload sample dataset first to view analytics.")

# ====================
# TAB 5: ABOUT
# ====================
with tabs[4]:
    st.header("About ResistAI")
    st.markdown("""
    **ResistAI** is a machine learning web application for predicting antimicrobial resistance patterns.
    
    ### How it Works
    1. **Data Ingestion**: Takes tabular clinical/microbiology data.
    2. **Preprocessing**: Automatically imputes missing values and encodes categorical data.
    3. **Training**: Uses advanced ensemble tree algorithms (Random Forests, XGBoost).
    4. **Prediction**: Classifies input as R/S/I with confidence intervals.
    
    ### Architecture
    - **Frontend**: Streamlit + Custom CSS
    - **Backend Pipeline**: Scikit-Learn + Pandas
    
    ### Future Scope
    - Integration with laboratory APIs (e.g., LIS systems).
    - Genomic sequence-based prediction.
    - Expansion to real-time epidemiological dashboards.
    """)
