def get_recommendations(prediction, confidence, species=None):
    """
    Rule-based recommendation engine for decision support.
    DO NOT USE FOR CLINICAL DIAGNOSIS.
    """
    recs = []
    
    recs.append("⚠️ **MEDICAL DISCLAIMER**: These recommendations are generated by an AI prototype for educational purposes only. Do not use for clinical decision-making.")
    
    if prediction == "Susceptible":
        if confidence > 80:
            recs.append("✅ High confidence that the tested antibiotic may be effective.")
            recs.append("-> Suggestion: Standard dosing protocols may be appropriate pending local guidelines.")
        else:
            recs.append("✅ Moderate confidence that the tested antibiotic may be effective.")
            recs.append("-> Suggestion: Consider standard therapy but monitor patient response closely.")
            
    elif prediction == "Intermediate":
        recs.append("⚠️ Intermediate resistance predicted.")
        recs.append("-> Suggestion: Consider increasing dosage if pharmacokinetically safe, or test alternative broad-spectrum agents.")
        
    elif prediction == "Resistant":
        recs.append("❌ High risk of antibiotic resistance.")
        recs.append("-> Suggestion: Avoid this antibiotic as monotherapy. Consider combination therapy or alternative classes.")
        if species:
            recs.append(f"-> Note: Double check local antibiograms for typical {species} resistance patterns.")
            
    return recs
